version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt install jq yarn
      - node -v
      - yarn version
  pre_build:
    commands:
      - FOLDER_NAME=$(echo $(date '+%Y%m%d%H%M%S'))

  build:
    commands:
      - echo Build started on `date`
      - echo Building JS .....
      - envsubst < ./fe-env-template.yaml > .env
      - yarn install
      - yarn build
      - echo Copying /build to S3 ....
      - aws s3 cp --recursive ./build s3://$S3_DEPLOY_BUCKET/$FOLDER_NAME

  post_build:
    commands:
      - echo Build done on `date`
artifacts:
  files:
    - '**/*'
