export const DefaultFormChange: any = {
  damages: false,
  details_of_damages: false,
  police_report_no: false,
  suspicions_details: false,
  brief_description: false,
  action_taken: false,
  claim_approver: false,
  case_title: false,
  incident_timestamp: false,
  police_report_date: false,
  claim_time: false,
  site_name: false,
  suspicions: false,
}
