beforeEach(cy.login)

describe('Check Approval Ticket', () => {
    beforeEach( () => {
        cy.visit('help-desk/ticket')
        cy.intercept('GET', '**/help-desk/contact').as('getContact')
        cy.intercept('GET', '**/help-desk/ticket*').as('fetchTickets')
        cy.intercept('DELETE', '**/help-desk/ticket/**').as('deleteTicket')
        cy.wait('@fetchTickets').its('response.statusCode').should('eq', 200)
        cy.get('.table-responsive table').as('TicketTable')
    })

    it('Check Ticket With Status Pending Approval', () => {
        cy.get('.table-responsive > .table')
        .find('tbody > tr.align-middle')
        .filter(':contains("Pending Approval")')
        .find('td.sticky-cus > a[data-cy=viewTable]').click({force: true, multiple: true })
    })

    it('Check Approve Ticket and Assigned to Agent', () => {
        cy.get('.table-responsive > .table')
        .find('tbody > tr.align-middle')
        .filter(':contains("Pending Approval")')
        .find('td.sticky-cus > a[data-cy=viewTable]').click({force: true, multiple: true })
        cy.wait(25000)
        cy.get('[data-cy=approvalDropDown]').click({force: true})
        cy.get('[data-cy=approveRejectDropDown]').click({force: true})
        cy.get('.modal-title').should('contain', "Approval Ticket")
        cy.get('input[data-cy=approveTicket]').click({force: true})
        cy.get('[data-cy=assignedToAgent]')
        .click({force:true})
        cy.get('.select-agent-cypress')
        .click({force:true})
        .find('input#select-assign_user_guid')
        .type('Testing{enter}', {force: true})
    })

    it('Check Approve Ticket and Assigned to Team', () => {
        cy.get('.table-responsive > .table')
        .find('tbody > tr.align-middle')
        .filter(':contains("Pending Approval")')
        .find('td.sticky-cus > a[data-cy=viewTable]').click({force: true, multiple: true })
        cy.wait(25000)
        cy.get('[data-cy=approvalDropDown]').click({force: true})
        cy.get('[data-cy=approveRejectDropDown]').click({force: true})
        cy.get('.modal-title').should('contain', "Approval Ticket")
        cy.get('input[data-cy=approveTicket]').click({force: true})
        cy.get('[data-cy=assignedToTeam]')
        .click({force:true})
        cy.get('.select-team-cypress')
        .click({force:true})
        .find('input#select-assign_team_guid')
        .type('testing{enter}', {force: true})
    })    

    it('Check Rejection Ticket', () => {
        cy.get('.table-responsive > .table')
        .find('tbody > tr.align-middle')
        .filter(':contains("Pending Approval")')
        .find('td.sticky-cus > a[data-cy=viewTable]').click({force: true, multiple: true })
        cy.wait(25000)
        cy.get('[data-cy=approvalDropDown]').click({force: true})
        cy.get('[data-cy=approveRejectDropDown]').click({force: true})
        cy.get('.modal-title').should('contain', "Approval Ticket")
        cy.get('input[data-cy=rejectTicket]').click({force: true})
        cy.get('button[data-cy=saveApproval]').should('contain', "Save").click({force: true})
        cy.get('.modal-title').should('contain', "Reject Ticket")
    })
})
