beforeEach(cy.login)

describe('Check Assign Ticket', () => {
    beforeEach( () => {
        cy.visit('help-desk/ticket')
        cy.intercept('GET', '**/help-desk/contact').as('getContact')
        cy.intercept('GET', '**/help-desk/ticket*').as('fetchTickets')
        cy.intercept('DELETE', '**/help-desk/ticket/**').as('deleteTicket')
        cy.wait('@fetchTickets').its('response.statusCode').should('eq', 200)
        cy.get('.table-responsive table').as('TicketTable')
    })

    it('Check Ticket With Status ToDo', () => {
        cy.get('.table-responsive > .table')
        .find('tbody > tr.align-middle')
        .filter(':contains("To Do")')
        .find('td.sticky-cus > a[data-cy=viewTable]').click({force: true, multiple: true })
    })

    it('Check Assign Ticket to Approver', () => {
        cy.get('.table-responsive > .table')
        .find('tbody > tr.align-middle')
        .filter(':contains("To Do")')
        .find('td.sticky-cus > a[data-cy=viewTable]').click({force: true, multiple: true })
        cy.wait(25000)
        cy.get('[data-cy=todoDropDown]').click({force: true, multiple: true })
        cy.get('[data-cy=assigneeTicket]').click({force: true, multiple: true })
        cy.get('.modal-title').should('contain', "Ticket Assigned")
        cy.get('input[data-cy=assignedToApprover]').click({force: true, multiple: true })
        cy.get('.select_approver_guid_cypress')
        .click({force:true})
        // .find('div#react-select-7-placeholder')
        // .should('contain', "Select Approver")
    })

    it('Check Assign Ticket to Agent', () => {
        cy.get('.table-responsive > .table')
        .find('tbody > tr.align-middle')
        .filter(':contains("To Do")')
        .find('td.sticky-cus > a[data-cy=viewTable]').click({force: true, multiple: true })
        cy.wait(25000)
        cy.get('[data-cy=todoDropDown]').click({force: true, multiple: true })
        cy.get('[data-cy=assigneeTicket]').click({force: true, multiple: true })
        cy.get('.modal-title').should('contain', "Ticket Assigned")
        cy.get('input[data-cy=assignedToAgent]').click({force: true, multiple: true })
        cy.get('.select_agent_guid_cypress')
        .click({force:true})
        // .find('div#react-select-7-placeholder')
        // .should('contain', "Select Agent")
    })

    it('Check Assign Ticket to Team', () => {
        cy.get('.table-responsive > .table')
        .find('tbody > tr.align-middle')
        .filter(':contains("To Do")')
        .find('td.sticky-cus > a[data-cy=viewTable]').click({force: true, multiple: true })
        cy.wait(25000)
        cy.get('[data-cy=todoDropDown]').click({force: true, multiple: true })
        cy.get('[data-cy=assigneeTicket]').click({force: true, multiple: true })
        cy.get('.modal-title').should('contain', "Ticket Assigned")
        cy.get('input[data-cy=assignedToTeam]').click({force: true, multiple: true })
        cy.get('.select_team_guid_cypress')
        .click({force:true})
        // .find('div#react-select-7-placeholder')
        // .should('contain', "Select Team")
    })
})
