export const planDescription: any = [
  {
    id: 1,
    name: 'Standard',
    feature_name: 'Core Features',
    plan_group: 3,
    feature_lists: [
      {title: 'Standard Asset Management', feature: 'yes'},
      {title: 'Limited Custom User Group', feature: 'yes'},
      {title: 'Dashboard & Reports​ ', feature: 'yes'},
      {title: 'Alert & Notifications', feature: 'yes'},
      {title: 'App Support', feature: 'yes'},
      {title: 'Audit', feature: 'no'},
      {title: 'Priority Support', feature: 'no'},
      {title: 'Unlimited Users', feature: 'no'},
      {title: 'Asset Check In / Out', feature: 'no'},
    ],
    feature_change_lists: [{title: 'Audit'}],
  },
  {
    id: 2,
    name: 'Professional',
    feature_name: 'Core Features Plus',
    plan_group: 4,
    feature_lists: [
      {title: 'Pro Asset Management', feature: 'yes'},
      {title: 'Custom User Management', feature: 'yes'},
      {title: 'Dashboard & Reports​ ', feature: 'yes'},
      {title: 'Alert & Notifications', feature: 'yes'},
      {title: 'App Support', feature: 'yes'},
      {title: 'Audit', feature: 'yes'},
      {title: 'Priority Support', feature: 'no'},
      {title: 'Unlimited Users', feature: 'no'},
      {title: 'Asset Check In / Out', feature: 'no'},
    ],
    feature_change_lists: [
      {title: 'Priority Support'},
      {title: 'Unlimited Users'},
      {title: 'Asset Check In / Out'},
    ],
  },
  {
    id: 3,
    name: 'Advance',
    feature_name: 'Core Features Plus',
    plan_group: 5,
    feature_lists: [
      {title: 'Advanced Asset Management', feature: 'yes'},
      {title: 'Advanced User Management', feature: 'yes'},
      {title: 'Dashboard & Reports​ ', feature: 'yes'},
      {title: 'Alert & Notifications', feature: 'yes'},
      {title: 'App Support', feature: 'yes'},
      {title: 'Audit', feature: 'yes'},
      {title: 'Priority Support', feature: 'yes'},
      {title: 'Unlimited Users', feature: 'yes'},
      {title: 'Asset Check In / Out', feature: 'yes'},
    ],
    feature_change_lists: [],
  },
]
